cram/async/reader/data_container/compression_header/encoding: Add BYTE_ARRAY_LEN encoding reader
This limits BYTE_ARRAY_LEN encodings to be anything other than
BYTE_ARRAY_LEN, which avoid recursion: `error[E0733]: recursion in an
`async fn` requires boxing`.